services:
  mytask:
    build:
      context: ./ass1
    container_name: my-task
    ports:
      - "80:80"
    volumes:
      - mytask-data:/usr/share/nginx/html

volumes:
 mytask-data: { }
   # networks:
